# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MfaAuth < Formula
  desc "Helper tool to store and run "
  homepage ""
  version "0.0.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.5/mfa-auth_0.0.5_darwin_amd64.tar.gz"
      sha256 "5a9fccfc33785552adfd9cc9160952a9c5a490a94ea0466c5f403137de2407f1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.5/mfa-auth_0.0.5_linux_amd64.tar.gz"
      sha256 "e54826cdf62f148f8a7fdf8f95d39cce22f273617447ab75bd03d8ffd9faa03b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.5/mfa-auth_0.0.5_linux_arm64.tar.gz"
      sha256 "8e0e0455673184e1f629091ab006c043c88c8383c65c17615560556f0c6b6962"
    end
  end

  def install
    bin.install "program"
  end

  def caveats; <<~EOS
    Just use the inbuilt help
  EOS
  end
end
