# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MfaAuth < Formula
  desc "Helper tool to store and run "
  homepage ""
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_darwin_amd64.tar.gz"
      sha256 "54f5bff4349ee3e609f84d67791f1505b043b3dcec39c03685508b21c01db963"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_amd64.tar.gz"
      sha256 "b827308a37ff95284d7267208a371d74caa64c9bbe2b10f883ca00583dfb9a8d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rajeshg007/mfa-auth/releases/download/v0.0.3/mfa-auth_0.0.3_linux_arm64.tar.gz"
      sha256 "a7314bf9f52d4ec04412ab1b6848b81bb07496c1c64a4ec53ec61d9f8ac6124f"
    end
  end

  def install
    bin.install "mfa-auth"
  end

  def caveats; <<~EOS
    Just use the inbuilt help
  EOS
  end
end
